Userstory3
DenisKorkmaz/Capstone-Project-News-App pull request #6
Opened 2023-08-10 13:55 UTC by DenisKorkmaz

Please check :)

2023-08-10 14:56 UTC, Roland-Hufnagel approved these changes
Please make sure to fit your userstory. I cannot see a real summery in the vercel-preview.

2023-08-10 14:56 UTC, Roland-Hufnagel commented on components/ThreeDotsMenü/ThreeDotMenü.js
> +            </Link>
Here you have a ``<a>``tag inside a ``<Link>``tag. What's the reason?

2023-08-10 14:57 UTC, Roland-Hufnagel requested changes
Please make sure to fit your userstory. I cannot see a real summery in the vercel-preview.

2023-08-10 15:08 UTC, DenisKorkmaz commented
@Roland-Hufnagel the API has a limit of 100 requests. To ensure that no empty data is displayed, I implemented default text as a fallback. Tomorrow, 100 new requests should be possible.

2023-08-11 10:28 UTC, Kheirah requested changes
Well done!

Your app functions properly, but you could improve on how you manage the state. Currently it's managed by a component. Lift up your state and its management to handle state only at one place instead of at the component level which renders at several places.

Also have a look at the css file and switch to using `styled-components`.

2023-08-11 10:28 UTC, Kheirah commented on pages/styles.css
Instead of raw CSS use `styled-components` for styling.

2023-08-11 10:28 UTC, Kheirah commented on components/ThreeDotsMenü/ThreeDotMenü.js
> +  }
You don't need the outer braces.
```suggestion
      if (isFavorite) {
        newFavorites = newFavorites.filter(
          (favorite) => favorite.shareURL !== article.shareURL
        );
      } else {
        newFavorites.push(article);
      }
      setFavorites(newFavorites);
      setIsFavorite(!isFavorite);
    }
```

2023-08-11 10:28 UTC, Kheirah commented on components/ThreeDotsMenü/ThreeDotMenü.js
> +  }, [favorites, article.shareURL]);
The state of marked favorites should not be specific to the `ThreeDotMenu` component.
The component shouldn't care about the list of favorites. It should only be responsible for opening and closing its menu. This is called **separation of concerns.** The component shouldn't be concerned with managing the localStorage state.

Apart from that, there's another reason which is technical: The `ThreeDotsMenu` component is rendered once for every article you display. If you display 20 articles you render this component 20 times. And for every one of these 20 `ThreeDotMenus` you have a separate `state` and `useEffect`. But you only need to manage your state _once._

Lift up the state and the handle functions to a higher level and manage your state from there. Pass down your state to components that rely on it, like this component.

2023-08-11 10:28 UTC, Kheirah commented on components/ThreeDotsMenü/ThreeDotMenü.js
> +              rel="noopener noreferrer">
Very good! Security comes first.

2023-08-11 10:28 UTC, Kheirah commented on components/ThreeDotsMenü/styles.js
> +export const StyledLink = styled.a`
Is there a reason why this is a normal anchor tag instead of the `Link` component?

2023-08-14 09:53 UTC, Roland-Hufnagel approved these changes
Hi Denis, you lifted up the state one level, but the ArticleCard is also rendered twenty times or more. Since Kheirah mentioned the separation of concerns, you should lift it up one more level. But it is up to you to implement this.

2023-08-14 13:24 UTC, merged